apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: xpokorny/ambulance-ufe
  newName: xpokorny/ambulance-ufe
  newTag: 1.0.2
- name: xpokorny/ambulance-wl-webapi
  newName: xpokorny/ambulance-wl-webapi
  newTag: 1.0.2