apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xpoky-ambulance-ufe-content
spec:
  microFrontend: xpoky-ambulance-ufe
  element: xpoky-ambulance-wl-app
  attributes:
    - name: base-path
      value: /xpoky-ambulance-wl/
    - name: api-base
      value: http://localhost:5000/api
    - name: ambulance-id
      value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xpoky-ambulance-wl(/.*)?$"