apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xpoky-ambulance-ufe-link
spec:
  microFrontend: polyfea-md-shell # referencia na microfrontend, z ktorého sa načíta element
  element: polyfea-md-app # element, ktorý bude vložený na stránku
  attributes: # atribúty elementu polyfea-md-app
    - name: headline
      value: Medical Appointment Scheduling System
    - name: short-headline
      value: Medical Appointment Scheduling System
    - name: supporting-text
      value: |
        Atomate and manage the process of scheduling, rescheduling, and canceling medical appointments between patients and healthcare providers
    - name: material-icon
      value: home_health
    - name: href # presmerovanie po kliknutí na element polyfea-md-app
      value: ./xpoky-ambulance-wl
  priority: 10
  displayRules: # pravidlá, kde sa má element vložiť v obálke
    - anyOf:
      - context-name: applications
      - context-name: rail-content
      - context-name: drawer-content