apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ../../../infrastructure/polyfea
- ../../../infrastructure/fluxcd
- ../../../infrastructure/envoy-gateway
- ../../../infrastructure/cert-manager

components:
- ../../../components/version-developers