apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# check the version is up-to-date
- https://github.com/cert-manager/cert-manager/releases/download/v1.13.1/cert-manager.yaml
- development.issuer.yaml
- lets-encrypt.issuer.yaml

patches:
- patch: |-
   - op: add
     path: /spec/template/spec/containers/0/args/-
     value: --feature-gates=ExperimentalGatewayAPISupport=true
  target:
    kind: Deployment
    name: cert-manager
    namespace: cert-manager